# Generated by Django 2.0.3 on 2018-04-08 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20180408_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='Edit')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
