# Generated by Django 2.0.3 on 2018-04-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user_now',
        ),
    ]
