# Generated by Django 2.0.3 on 2018-04-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sid',
            field=models.CharField(blank=True, max_length=50, unique=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=1),
        ),
    ]
